In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

2.3.0


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#0-D Arrays
import numpy
arr=numpy.array(42)
print(arr)

42


In [7]:
#1-D array
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

          


[1 2 3 4 5]


In [8]:
#2-D array
import numpy
arr1=numpy.array([[1,2,3],
                 [4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [9]:
#3-D array
import numpy
arr=numpy.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
print(arr1.ndim)

2


In [11]:
#Access array elements
import numpy
arr=numpy.array([1,2,3,4])
print(arr[0])

1


In [12]:
#access 2-D array
arr=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd elements on 1st row:',arr[0,1])

2nd elements on 1st row: 2


In [13]:
# Accessing elements using slicing
arr=numpy.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [14]:
#Negative slicing
arr=numpy.array([1,2,3,4,5])
print(arr[-4:-1])


[2 3 4]


In [15]:
#Checking datatype of array
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)



int64


In [18]:
arr=np.array([[1,2,3,4],[5,6,7,8],[3,3,4,5]])
print(arr.shape)


(3, 4)


In [17]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
